import React from 'react';
import { useNavigate } from 'react-router-dom';
import { Sparkles } from 'lucide-react';
import { useAuth } from '../hooks/useAuth.js';
import SEOHead from '../components/SEOHead.jsx';
import STEAHeader from "../components/shared/STEAHeader.jsx";

const TOOLS = [['🎬', 'Video Ideas', 'Fresh concepts for your next video.'], ['🖼', 'Thumbnail Templates', 'Clear, high-impact visual starting points.'], ['🤖', 'AI Prompts', 'Prompts for faster creative work.'], ['📱', 'Social Media Tips', 'Practical ways to improve your posts.'], ['🎨', 'Design Resources', 'Useful assets and design inspiration.'], ['📈', 'Growth Tips', 'Simple systems to grow your audience.']];
export default function SteaCreatorsPage() {
  const { user } = useAuth(); const navigate = useNavigate();
  return <div style={{ minHeight: '100vh', background: '#F8FAFC', color: '#111827', fontFamily: "'Instrument Sans',system-ui,sans-serif" }}><SEOHead title="STEA Creators" description="Ideas, templates, prompts and tools for creators." /><STEAHeader title="Creators" user={user} /><main style={{ width: 'min(1120px,100%)', margin: '0 auto', padding: '32px 16px 52px' }}><section style={{ maxWidth: 690, marginBottom: 28 }}><p style={{ margin: '0 0 8px', color: '#9A7700', fontSize: 11, fontWeight: 900, letterSpacing: '.13em', textTransform: 'uppercase' }}>Creator hub</p><h1 style={{ margin: 0, fontSize: 'clamp(32px,7vw,52px)', letterSpacing: '-.05em', lineHeight: 1.02 }}>Create better content with STEA.</h1><p style={{ margin: '14px 0 20px', color: '#4B5563', fontSize: 16, lineHeight: 1.65 }}>Tools, ideas, templates and tips to help creators grow faster.</p><button onClick={() => navigate('/creators/apply')} style={{ padding: '12px 16px', border: 0, borderRadius: 11, background: '#2563EB', color: '#fff', fontWeight: 800, cursor: 'pointer' }}>Start Creating</button></section><section style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit,minmax(230px,1fr))', gap: 14 }}>{TOOLS.map(([icon, title, desc]) => <article key={title} style={{ minHeight: 180, padding: 20, display: 'flex', flexDirection: 'column', border: '1px solid #E5E7EB', borderRadius: 18, background: '#fff', boxShadow: '0 8px 22px rgba(17,24,39,.05)' }}><span style={{ fontSize: 25 }}>{icon}</span><h2 style={{ margin: '15px 0 8px', fontSize: 18 }}>{title}</h2><p style={{ flex: 1, margin: 0, color: '#4B5563', fontSize: 14, lineHeight: 1.55 }}>{desc}</p><span style={{ alignSelf: 'flex-start', marginTop: 15, padding: '6px 9px', borderRadius: 999, background: '#F1F5F9', color: '#6B7280', fontSize: 11, fontWeight: 800 }}>Coming soon</span></article>)}</section><section style={{ marginTop: 24, padding: 18, display: 'flex', gap: 11, alignItems: 'center', border: '1px solid rgba(212,175,55,.34)', borderRadius: 16, background: '#FFFCF3' }}><Sparkles size={20} color="#D4AF37" /><span style={{ color: '#5F4A00', fontSize: 13, fontWeight: 700 }}>New creator resources are being prepared. Check back soon.</span></section></main></div>;
}
