export const TOKENS = {
  page: "var(--stea-page)",
  surface: "var(--stea-surface)",
  panel: "var(--stea-panel)",
  panel2: "var(--stea-panel2)",
  border: "var(--stea-border)",
  borderHi: "var(--stea-border-hi)",
  text: "var(--stea-text)",
  text2: "var(--stea-text2)",
  text3: "var(--stea-text3)",
  gold: "var(--stea-gold)",
  goldHi: "var(--stea-gold-hi)",
  goldSoft: "var(--stea-gold-soft)",
  hover: "var(--stea-hover)",
  danger: "var(--stea-danger)",
  success: "var(--stea-success)",
  contentMax: 1440,
  radiusSm: 10,
  radius: 14,
  radiusLg: 18,
  radiusXl: 22,
  zBase: "var(--stea-z-base, 0)",
  zContent: "var(--stea-z-content, 10)",
  zHero: "var(--stea-z-hero, 30)",
  zRail: "var(--stea-z-rail, 40)",
  zHeroActive: "var(--stea-z-hero-active, 45)",
  zSearchDropdown: "var(--stea-z-search-dropdown, 50)",
  zHeader: "var(--stea-z-header, 60)",
  zBottomNav: "var(--stea-z-bottom-nav, 70)",
  zToast: "var(--stea-z-toast, 80)",
  zModalBackdrop: "var(--stea-z-modal-backdrop, 90)",
  zModal: "var(--stea-z-modal, 100)",
  zSplash: "var(--stea-z-splash, 200)",
};

export const G = TOKENS.gold;
export default TOKENS;
